### PR TITLE
Add support for the playlistId attribute.

### LINKED ISSUE #1: Add support for a playlistId attribute
As an alternative to powering the wall via search, add support for a `playlistId` parameter.

Setting `playlistId` will cause any of the search-related attributes to be ignored.

### PR DESCRIPTION
**Pull request by jeffposnick**
@ebidel @addyosmani & co.:

This closes #1, by adding in support for a new `playlistId` attribute. If present, the search terms will be ignored, and if `wallTitle` isn't already set, the playlist's title will be used.

### CODE REVIEW

**Comment by jeffposnick** [comment]
Actually, I should hook up the `wallTitle` lookup to whenever `playlistId` changes. Let me do that first...

**Comment by ebidel** [comment]
Ping when ready.

**Comment by jeffposnick** [comment]
Okay, I think that will take care of it.

There's an edge case where `wallTitle` won't get updated if its published value is bound to a template variable (e.g. `wallTitle="{{wallTitle}}"`) since [`this.hasAttribute('wallTitle')`](https://github.com/GoogleWebComponents/google-youtube-video-wall/pull/4/files#diff-00b8b33646437e4a6460ca27984f4dbcR552) will be `true` in that case, but maybe that's not a big deal. If you have any suggestions for structuring the logic to avoid that possibility, I'd be interested to hear.

**Comment by addyosmani** [comment]
This change LGTM. It may be worth adding a note or TODO to explore addressing the bound templates edge-case just in case someone runs into it in the future.

**Pull request merged**
